version: '3.7'

services:
  api:
    image: mtsteo/challenge3-api
    ports:
      - "3001:3001"

  frontend:
    image: mtsteo/challenge3-front
    ports:
      - "80:80"
    depends_on:
      - api
